name: ETL Pipeline Demo

on:
  push:
    branches:
      - main

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run extract.py
        run: python .github/workflows/extract.py

  transform-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run transform.py
        run: python .github/workflows/transform.py

  load-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run load.py
        run: python .github/workflows/load.py
